app = "fraud-detection-lamine"

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [services.ports]
    handlers = ["http"]
    port = 80

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000